#!/usr/bin/env python3
"""Hard safety gate for automated article publishing.

This gate is intentionally conservative: it blocks obviously incomplete,
thin, duplicated, or legacy low-quality output before the workflow commits.
It does not rewrite content and never sends traffic.
"""
from pathlib import Path
import re
import sys

POSTS = Path("content/posts")
MIN_WORDS = 800
MIN_IMAGES = 4
MIN_H2 = 5
MIN_FAQ = 3

def frontmatter(text):
    if not text.startswith("+++"):
        return "", text
    end = text.find("\n+++\n", 3)
    if end == -1:
        return "", text
    return text[3:end], text[end + 5:]

def field(fm, name):
    m = re.search(rf"^{re.escape(name)}\s*=\s*(.+)$", fm, re.M)
    return m.group(1).strip() if m else ""

def quoted_value(v):
    m = re.match(r'^["\'](.*)["\']$', v)
    return m.group(1) if m else v

def word_count(body):
    return len(re.findall(r"\b[\w’'-]+\b", body))

def main():
    posts = [p for p in POSTS.glob("*.md") if p.name != ".gitkeep"]
    if not posts:
        print("CONTENT GATE: no posts found")
        return 0

    # The daily generator creates/updates one post per run. Validate the newest
    # file only; historical content is not modified by this gate.
    post = max(posts, key=lambda p: p.stat().st_mtime)
    text = post.read_text(encoding="utf-8")
    fm, body = frontmatter(text)

    errors = []
    title = quoted_value(field(fm, "title"))
    description = quoted_value(field(fm, "description"))

    if not title:
        errors.append("missing title")
    elif not 35 <= len(title) <= 100:
        errors.append(f"title length {len(title)} outside 35-100")

    if not description:
        errors.append("missing description")
    elif not 80 <= len(description) <= 220:
        errors.append(f"description length {len(description)} outside 80-220")

    words = word_count(body)
    if words < MIN_WORDS:
        errors.append(f"only {words} body words; minimum is {MIN_WORDS}")

    images = len(re.findall(r"!\[[^\]]*\]\([^\)]+\)", body))
    if images < MIN_IMAGES:
        errors.append(f"only {images} inline images; minimum is {MIN_IMAGES}")

    h2 = len(re.findall(r"^##\s+\S", body, re.M))
    if h2 < MIN_H2:
        errors.append(f"only {h2} H2 sections; minimum is {MIN_H2}")

    faq_count = len(re.findall(r"question\s*=", fm, re.I))
    if faq_count < MIN_FAQ:
        errors.append(f"only {faq_count} FAQ questions; minimum is {MIN_FAQ}")

    forbidden_markers = [
        "generated by groq",
        "groq api",
        "lorem ipsum",
        "as an ai language model",
    ]
    lower = text.lower()
    for marker in forbidden_markers:
        if marker in lower:
            errors.append(f"forbidden legacy marker: {marker}")

    # Prevent exact-title duplication across the existing library.
    for other in posts:
        if other == post:
            continue
        ofm, _ = frontmatter(other.read_text(encoding="utf-8"))
        other_title = quoted_value(field(ofm, "title"))
        if title and other_title and title.casefold() == other_title.casefold():
            errors.append(f"duplicate title with {other.name}")
            break

    if errors:
        print(f"CONTENT GATE: BLOCKED {post}")
        for error in errors:
            print(f" - {error}")
        return 1

    print(
        f"CONTENT GATE: PASS {post.name} | words={words} "
        f"images={images} h2={h2} faq={faq_count}"
    )
    return 0

if __name__ == "__main__":
    sys.exit(main())
